/* Reconstructed Commander Keen 1-3 Source Code
 * Copyright (C) 2021-2026 K1n9_Duk3
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef __SOUNDS__
#define __SOUNDS__

// sound names, taken from SOUNDS.CK3

typedef enum
{	
	WLDWALKSND = 1,
	WLDBLOCKSND,
	WLDENTERSND,
	KEENWALKSND,
	KEENBLOKSND,
	KEENJUMPSND,
	KEENLANDSND,
	KEENDIESND,
	GOTBONUSSND,
	GOTITEMSND,
	GOTPARTSND,
	KEENFIRESND,
	KEENPOGOSND,
	POGOJUMPSND,
	LVLDONESND,
	GAMEOVERSND,
	HISCORESND,
	TELEPORTSND,
	CHUNKSMASHSND,
	GOINDOORSND,
	BUMPHEADSND,
	USEKEYSND,
	CANNONFIRESND,
	SLAMSND,
	CLICKSND,
	CRYSTALSND,
	PLUMMETSND,
	EXTRAMANSND,
	YORPBUMPSND,
	KEENWLK2SND,
	YORPBOPSND,
	GETCARDSND,
	DOOROPENSND,
	YORPSCREAMSND,
	GARGSCREAMSND,
	GUNCLICKSND,
	SHOTHITSND,
	TANKFIRESND,
	VORTSCREAMSND,
	KEENSICLESND,
	KEENSLEFTSND,
	ANKHSND,
	MEEPSND,
	MORTIMERSND,
	FOOTSLAMSND,
	LASTSOUND	// marks the end of the sound names, never used
} soundnames;

#endif