"""
Bake a 1-bit 8x8 bitmap font into a C header for the launcher.

Why bake rather than load at runtime: the launcher must not depend on
SDL_ttf (not vendored) and must not embed the GAMES' font data (that would
mean redistributing id's art).  Rendering a system monospace font offline
gives crisp, licence-clean glyphs with no runtime dependency at all.

Chunky-by-design: rendered at 8x8 with no antialiasing (mode "1"), so it
scales up as hard pixels alongside the games' own artwork.

Usage:  python gen_font.py            (writes launcher_font.h)
"""

import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FIRST, LAST = 32, 126          # printable ASCII
W, H = 8, 12          # taller cell: far more legible than 8x8


def pick_font():
    for name, size in (("lucon.ttf", 11), ("consola.ttf", 11), ("cour.ttf", 12)):
        path = os.path.join(r"C:\Windows\Fonts", name)
        if os.path.exists(path):
            return ImageFont.truetype(path, size), name
    raise SystemExit("no monospace system font found")


def main():
    font, name = pick_font()
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (W, H), 0)
        d = ImageDraw.Draw(img)
        d.fontmode = "1"                      # no antialiasing: hard pixels
        d.text((0, 0), chr(code), font=font, fill=1)
        bits = []
        for y in range(H):
            byte = 0
            for x in range(W):
                if img.getpixel((x, y)):
                    byte |= 1 << (7 - x)      # MSB = leftmost pixel
            bits.append(byte)
        rows.append((code, bits))

    out = [
        "/*",
        " * GENERATED by gen_font.py -- do not edit by hand.",
        f" * {W}x{H} 1-bit glyphs for ASCII {FIRST}..{LAST}, baked from the system",
        f" * monospace font ({name}) with antialiasing off, so it scales as hard",
        " * pixels next to the games' own art.  Baked so the launcher needs no",
        " * font library at runtime, and so no game art is redistributed.",
        " * Bit 7 of each byte is the leftmost pixel.",
        " */",
        "",
        f"#define LFONT_FIRST {FIRST}",
        f"#define LFONT_LAST {LAST}",
        f"#define LFONT_W {W}",
        f"#define LFONT_H {H}",
        "",
        "static const unsigned char lfont[LFONT_LAST - LFONT_FIRST + 1][LFONT_H] = {",
    ]
    for code, bits in rows:
        ch = chr(code)
        label = "space" if ch == " " else ch.replace("\\", "\\\\").replace("*/", "")
        out.append("\t{" + ", ".join(f"0x{b:02X}" for b in bits) + f"}},  /* {label} */")
    out.append("};")

    path = os.path.join(HERE, "launcher_font.h")
    open(path, "w", newline="").write("\n".join(out) + "\n")
    print(f"wrote {path}: {len(rows)} glyphs from {name}")


if __name__ == "__main__":
    main()
