"""
Bake a THICK 1-bit display font for the launcher's headers and tile labels.

Same licence-clean approach as gen_font.py (system font, rendered offline,
no game data), but bolder and larger so the shell reads as the Keen era of
DOS rather than a text-mode utility: a heavy face at 12x16 whose glyphs the
launcher then draws with an outline + emboss (bright top-left, dark
bottom-right) for the chunky bevelled look of the games' own title art.

Usage:  python gen_font_big.py        (writes launcher_font_big.h)
"""

import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
FIRST, LAST = 32, 126
W, H = 12, 16

# 16 bits per row on disk (glyphs are 12 wide)


def pick_font():
    # heavy faces first; all ship with Windows
    for name, size in (("arialbd.ttf", 14), ("verdanab.ttf", 13),
                       ("tahomabd.ttf", 14), ("arial.ttf", 14)):
        path = os.path.join(r"C:\Windows\Fonts", name)
        if os.path.exists(path):
            return ImageFont.truetype(path, size), name
    raise SystemExit("no bold system font found")


def main():
    font, name = pick_font()
    rows = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (W, H), 0)
        d = ImageDraw.Draw(img)
        d.fontmode = "1"
        # centre each glyph in the cell so the row reads evenly
        bbox = d.textbbox((0, 0), chr(code), font=font)
        gw = bbox[2] - bbox[0]
        d.text(((W - gw) // 2 - bbox[0], -bbox[1] + 1), chr(code),
               font=font, fill=1)
        bits = []
        for y in range(H):
            word = 0
            for x in range(W):
                if img.getpixel((x, y)):
                    word |= 1 << (15 - x)
            bits.append(word)
        rows.append((code, bits))

    out = [
        "/*",
        " * GENERATED by gen_font_big.py -- do not edit by hand.",
        " * Source face: %s (system font, no game data)." % name,
        " */",
        "#define LBFONT_FIRST %d" % FIRST,
        "#define LBFONT_LAST %d" % LAST,
        "#define LBFONT_W %d" % W,
        "#define LBFONT_H %d" % H,
        "static const unsigned short lbfont[%d][%d] = {" % (LAST - FIRST + 1, H),
    ]
    for code, bits in rows:
        out.append("\t{%s}, /* %s */" %
                   (",".join("0x%04X" % b for b in bits),
                    chr(code).replace("*", "star").replace("\\", "bs")))
    out.append("};")
    with open(os.path.join(HERE, "launcher_font_big.h"), "w") as f:
        f.write("\n".join(out) + "\n")
    print("launcher_font_big.h written (%s)" % name)


if __name__ == "__main__":
    main()
