"""
Generate k13_thinktable.inc: the registry that lets a savegame name the
behaviour functions an object is currently running.

Keen 1-3 objects hold RAW FUNCTION POINTERS (think, contact) rather than an
index into a table of actions the way Keen 4-6 does, so a saved object cannot
just store a number -- there is nothing stable to store.  This emits a table
of { "name", pointer } pairs so the saver can turn a pointer into an index and
the loader can turn it back.

Generated rather than hand-written because the list is long (52 entries in
ep1, 65 in ep3) and hand-maintaining it would rot the moment behaviour code
changes.  Re-run after touching any *ACT.C.

Each episode links only its own KEEN<ep>ACT.C (which #includes KEENACTS.C), so
the table is emitted per episode.  A name that does not exist in an episode
becomes a link error -- loud, which is what we want.

Usage:  python gen_thinktable.py        (writes k13_thinktable.inc)
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# ".think = Foo", "->contact = (objcontact)Bar", "->think = &Baz"
ASSIGN = re.compile(
    r"(?:\.|->)\s*(think|contact)\s*=\s*"
    r"(?:\(\s*[A-Za-z_][A-Za-z0-9_ ]*\s*\)\s*)?"     # optional cast
    r"&?\s*([A-Za-z_][A-Za-z0-9_]*)"
)

SHARED = ["KEENMAIN.C", "KEENDEMO.C", "KEENSCRN.C", "IDLIBC.C"]


def preprocess(path, ep):
    """Run the source through the C preprocessor for this episode.

    Scanning raw text is not good enough: KEENACTS.C is full of
    '#if (EPISODE == n)' blocks, so a plain regex collects behaviour
    functions belonging to other episodes and the generated table then fails
    to link (that is exactly how 'FoobWalk', a Keen 2 enemy, ended up in the
    Keen 1 table).  Letting cl.exe resolve the conditionals fixes it.
    """
    import subprocess
    cmd = ("cl /nologo /EP /DEPISODE=%d /DVERSION=0x0131 /DK13_PORT "
           "/D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS "
           '/FI"%s" /I"%s" "%s"' %
           (ep, os.path.join(HERE, "k13_compat.h"), HERE, os.path.join(HERE, path)))
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True,
                       errors="replace", cwd=HERE)
    if not r.stdout:
        raise SystemExit(f"preprocessing {path} for ep{ep} produced nothing.\n"
                         f"Run this from a shell with MSVC on PATH "
                         f"(vcvars64.bat).\n{r.stderr[:400]}")
    return r.stdout


def scan(paths, ep):
    """Return (think_names, contact_names) assigned anywhere in paths."""
    think, contact = set(), set()
    for p in paths:
        if not os.path.exists(os.path.join(HERE, p)):
            continue
        for field, name in ASSIGN.findall(preprocess(p, ep)):
            if name in ("NULL", "null") or name.isdigit():
                continue
            (think if field == "think" else contact).add(name)
    return think, contact


def main():
    out = [
        "/*",
        " * GENERATED by gen_thinktable.py -- do not edit by hand.",
        " *",
        " * Maps object behaviour functions to stable ids so a savegame can",
        " * record which one an object is running.  Keen 1-3 stores raw",
        " * function pointers in objtype/pobjtype, so there is no engine-side",
        " * index to reuse (unlike Keen 4-6's action table).",
        " *",
        " * pobjs use this table too.  Their `type` field does NOT imply the",
        " * think pointer: POBJ_BRIDGE runs BridgeCreate, BridgeRemove or",
        " * NullPThink depending on where it is in its cycle.",
        " */",
        "",
    ]
    for ep in (1, 2, 3):
        act = f"KEEN{ep}ACT.C"
        think, contact = scan([act] + SHARED, ep)
        names = sorted(think | contact)
        out.append(f"#if (EPISODE == {ep})")
        out.append(f"/* {len(think)} think + {len(contact)} contact "
                   f"= {len(names)} distinct */")
        out.append("static const K13_FnEntry k13_fntable[] = {")
        for n in names:
            out.append(f'\t{{"{n}", (void *)&{n}}},')
        out.append("};")
        out.append("#endif")
        out.append("")
        print(f"ep{ep}: {len(names)} entries "
              f"({len(think)} think, {len(contact)} contact)")

    path = os.path.join(HERE, "k13_thinktable.inc")
    open(path, "w", newline="").write("\n".join(out))
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
